kind: Deployment
apiVersion: apps/v1
metadata:
  name: service-registry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: srinu
          image: qualitto007/service-registry:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
