---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-registry
      version: blue
  template:
    metadata:
      name: service-registry
      labels:
        app: service-registry
        version: blue
    spec:
      containers:
      - name: service-registry
        image: qualitto007/service-registry:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: service-registry
  labels:
    app: service-registry
spec:
  selector:
    app: service-registry
    version: blue
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 80
